[wip] tweak tempest
calling tweak script from run-tempest-* scripts

diff --git a/bin/tweak-tempest b/bin/tweak-tempest
--- a/bin/tweak-tempest
+++ b/bin/tweak-tempest
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script teaks the tempest config files slightly
+# This script tweaks the tempest config files slightly
 # this helps account for settings that may not be exposed via devstack
 
 function set_value_if_unset {
@@ -16,11 +16,17 @@ function set_value_if_unset {
   fi
 }
 
-
 DEVSTACK_DIR=""
 if [ -d /get/devstack ]; then
   DEVSTACK_DIR="/git/devstack"
 fi
+
+if [ ! -d "${DEVSTACK_DIR}" ]; then
+  echo "Unable to find the devstack directory"
+  echo "Please export it as the DEVSTACK_DIR environment variable"
+  exit 1
+fi
+
 # devstack contains some handy code to manipulate ini files
 source "${DEVSTACK_DIR}/inc/ini-config"
 
